In [37]:
from pyproj import Proj, transform
import numpy as np
import pandas  as pd

# Projection 정의
# UTM-K
proj_UTMK = Proj(init='epsg:5178') # UTM-K(Bassel) 도로명주소 지도 사용 중

# WGS1984
proj_WGS84 = Proj(init='epsg:4326') # Wgs84 경도/위도, GPS사용 전지구 좌표

# UTM-K -> WGS84 샘플
x1, y1 = 898420,1834000
x2, y2 = transform(proj_UTMK, proj_WGS84,x1,y1)
print(x2,y2)

# WGS84 -> UTM-K 샘플
x1, y1 = 126.36577531899309, 36.49827683619738
x2, y2 = transform(proj_WGS84, proj_UTMK, x1, y1)
print(x2,y2)

# x, y 컬럼을 이용하여 UTM-K좌표를 WGS84로 변환한 Series데이터 반환
def transform_utmk_to_w84(df):
    return pd.Series(transform(proj_UTMK, proj_WGS84, df['경도'], df['위도']), index=['경도', '위도'])

# x, y 컬럼을 이용하여 UTM-K좌표를 WGS84로 변환한 Series데이터 반환
def transform_w84_to_utmk(df):
    return pd.Series(transform(proj_WGS84, proj_UTMK, df['경도'], df['위도']), index=['경도', '위도'])

df_utmk = pd.DataFrame([
                                        ['A', 961114.519726,1727112.269174],
                                        ['B', 940934.895125,1685175.196487],
                                        ['C', 1087922.228298,1761958.688262]
                                    ], columns=['id', '경도', '위도'])

df_w84 = pd.DataFrame([
                                        ['A', 127.068893, 35.541981],
                                        ['B', 126.849319, 35.162867],
                                        ['C', 128.471575, 35.852994]
                                    ], columns=['id', '경도', '위도'])

df_utmk[['경도_w84', '위도_w84']] = df_utmk.apply(transform_utmk_to_w84, axis=1)
df_w84[['경도_utmk', '위도_utmk']] = df_w84.apply(transform_w84_to_utmk, axis=1)

126.36360651676448 36.501031386374954
898610.6464965016 1833692.1432416283

C:\ProgramData\Anaconda3\lib\site-packages\pyproj\crs\crs.py:131: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\ProgramData\Anaconda3\lib\site-packages\pyproj\crs\crs.py:131: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
<ipython-input-37-456bb5484d8e>:14: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  x2, y2 = transform(proj_UTMK, proj_WGS84,x1,y1)
<ipython-input-37-456bb5484d8e>:19: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  x2, y2 = transform(proj_WGS84, proj_UTMK, x1, y1)
<ipython-input-37-456bb5484d8e>:24: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  return pd.Series(transform(proj_UTMK, proj_WGS84, df['경도'], df['위도']), index=['경도', '위도'])
<ipython-input-37-456bb5484d8e>:28: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  return pd.Series(transform(proj_WGS84, proj_UTMK, df['경도'], df['위도']), index=['경도', '위도'])

In [16]:
# 확인
df_utmk

  id            경도            위도      경도_w84     위도_w84
0  A  9.611145e+05  1.727112e+06  127.068893  35.541981
1  B  9.409349e+05  1.685175e+06  126.849319  35.162867
2  C  1.087922e+06  1.761959e+06  128.471575  35.852994

In [17]:
# 확인
df_w84

  id          경도         위도       경도_utmk       위도_utmk
0  A  127.068893  35.541981  9.611145e+05  1.727112e+06
1  B  126.849319  35.162867  9.409349e+05  1.685175e+06
2  C  128.471575  35.852994  1.087922e+06  1.761959e+06

In [4]:
# 데이터
df = pd.read_csv("merge_temp.csv", encoding='utf-8')
df.head()

,Unnamed: 0,상가업소번호,상권업종대분류명,상권업종중분류명,상권업종소분류명,시군구명,경도,위도,date,geometry,GRID_ID,지번주소,도로명주소
0,0,18921801,관광지,지역사찰,지역사찰,고성군,128.461232,38.450099,2021-06-01,POINT (128.461231846869 38.4500990879468),라아838503,NaN,NaN
1,1,20739840,관광지,해수욕장,해수욕장,고성군,128.509936,38.356723,2021-06-01,POINT (128.509936046267 38.3567228330802),라아882400,NaN,NaN
2,2,7231262,관광지,해수욕장,해수욕장,고성군,128.546412,38.300914,2021-06-01,POINT (128.546412289393 38.300913819225),라아914339,NaN,NaN
3,3,11385177,관광지,일반관광지,일반관광지,고성군,128.370069,38.404499,2021-06-01,POINT (128.370069234145 38.4044988845984),라아759452,NaN,NaN
4,4,14123105,관광지,토속/특산물/기념품매장,토속/특산물/기념품매장,고성군,128.535804,38.306674,2021-06-01,POINT (128.535803652593 38.3066740590294),라아905345,NaN,NaN

In [5]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [20]:
df.head()

,상가업소번호,상권업종대분류명,상권업종중분류명,상권업종소분류명,시군구명,경도,위도,date,geometry,GRID_ID,지번주소,도로명주소
0,18921801,관광지,지역사찰,지역사찰,고성군,128.461232,38.450099,2021-06-01,POINT (128.461231846869 38.4500990879468),라아838503,NaN,NaN
1,20739840,관광지,해수욕장,해수욕장,고성군,128.509936,38.356723,2021-06-01,POINT (128.509936046267 38.3567228330802),라아882400,NaN,NaN
2,7231262,관광지,해수욕장,해수욕장,고성군,128.546412,38.300914,2021-06-01,POINT (128.546412289393 38.300913819225),라아914339,NaN,NaN
3,11385177,관광지,일반관광지,일반관광지,고성군,128.370069,38.404499,2021-06-01,POINT (128.370069234145 38.4044988845984),라아759452,NaN,NaN
4,14123105,관광지,토속/특산물/기념품매장,토속/특산물/기념품매장,고성군,128.535804,38.306674,2021-06-01,POINT (128.535803652593 38.3066740590294),라아905345,NaN,NaN

In [27]:
df[['경도_utmk', '위도_utmk']] = df.apply(transform_w84_to_utmk, axis=1)
df

<ipython-input-15-8b76ca886cdb>:28: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  return pd.Series(transform(proj_WGS84, proj_UTMK, df['경도'], df['위도']), index=['경도', '위도'])

,상가업소번호,상권업종대분류명,상권업종중분류명,상권업종소분류명,시군구명,경도,위도,date,geometry,GRID_ID,지번주소,도로명주소,경도_utmk,위도_utmk
0,18921801,관광지,지역사찰,지역사찰,고성군,128.461232,38.450099,2021-06-01,POINT (128.461231846869 38.4500990879468),라아838503,NaN,NaN,1.084065e+06,2.050075e+06
1,20739840,관광지,해수욕장,해수욕장,고성군,128.509936,38.356723,2021-06-01,POINT (128.509936046267 38.3567228330802),라아882400,NaN,NaN,1.088429e+06,2.039760e+06
2,7231262,관광지,해수욕장,해수욕장,고성군,128.546412,38.300914,2021-06-01,POINT (128.546412289393 38.300913819225),라아914339,NaN,NaN,1.091686e+06,2.033602e+06
3,11385177,관광지,일반관광지,일반관광지,고성군,128.370069,38.404499,2021-06-01,POINT (128.370069234145 38.4044988845984),라아759452,NaN,NaN,1.076158e+06,2.044936e+06
4,14123105,관광지,토속/특산물/기념품매장,토속/특산물/기념품매장,고성군,128.535804,38.306674,2021-06-01,POINT (128.535803652593 38.3066740590294),라아905345,NaN,NaN,1.090751e+06,2.034231e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22037,16701470,음식,한식,한식,속초시,128.527841,38.205636,2021-06-01,POINT (128.527840766914 38.205635567253),NaN,강원도 속초시 노학동 1011-21,강원도 속초시 원암학사평길 184,1.090180e+06,2.023012e+06
22038,16697583,음식,한식,한식,고성군,128.553075,38.234269,2021-06-01,POINT (128.553074728263 38.2342692932055),NaN,강원도 고성군 토성면 인흥리 262,강원도 고성군 토성면 인흥길 118,1.092353e+06,2.026214e+06
22039,16768997,음식,한식,한식,고성군,128.424168,38.500550,2021-06-01,POINT (128.424167503715 38.5005498900511),NaN,강원도 고성군 현내면 대진리 111-5,강원도 고성군 현내면 한나루로 144-2,1.080774e+06,2.055641e+06
22040,16716191,음식,한식,한식,속초시,128.587245,38.190884,2021-06-01,POINT (128.587245252883 38.1908838887186),NaN,강원도 속초시 조양동 1550-6,강원도 속초시 엑스포로1길 26,1.095400e+06,2.021434e+06
22041,16725821,음식,한식,한식,속초시,128.582587,38.203710,2021-06-01,POINT (128.582587017547 38.2037098804093),NaN,강원도 속초시 청학동 632-32,강원도 속초시 번영로 38,1.094975e+06,2.022853e+06

# test

In [29]:
df_test = df.head()
df_test

,상가업소번호,상권업종대분류명,상권업종중분류명,상권업종소분류명,시군구명,경도,위도,date,geometry,GRID_ID,지번주소,도로명주소,경도_utmk,위도_utmk
0,18921801,관광지,지역사찰,지역사찰,고성군,128.461232,38.450099,2021-06-01,POINT (128.461231846869 38.4500990879468),라아838503,NaN,NaN,1.084065e+06,2.050075e+06
1,20739840,관광지,해수욕장,해수욕장,고성군,128.509936,38.356723,2021-06-01,POINT (128.509936046267 38.3567228330802),라아882400,NaN,NaN,1.088429e+06,2.039760e+06
2,7231262,관광지,해수욕장,해수욕장,고성군,128.546412,38.300914,2021-06-01,POINT (128.546412289393 38.300913819225),라아914339,NaN,NaN,1.091686e+06,2.033602e+06
3,11385177,관광지,일반관광지,일반관광지,고성군,128.370069,38.404499,2021-06-01,POINT (128.370069234145 38.4044988845984),라아759452,NaN,NaN,1.076158e+06,2.044936e+06
4,14123105,관광지,토속/특산물/기념품매장,토속/특산물/기념품매장,고성군,128.535804,38.306674,2021-06-01,POINT (128.535803652593 38.3066740590294),라아905345,NaN,NaN,1.090751e+06,2.034231e+06

In [30]:
df_test["GRID_ID"] = 0
df_test

<ipython-input-30-1d877ce5b32b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test["GRID_ID"] = 0

,상가업소번호,상권업종대분류명,상권업종중분류명,상권업종소분류명,시군구명,경도,위도,date,geometry,GRID_ID,지번주소,도로명주소,경도_utmk,위도_utmk
0,18921801,관광지,지역사찰,지역사찰,고성군,128.461232,38.450099,2021-06-01,POINT (128.461231846869 38.4500990879468),0,NaN,NaN,1.084065e+06,2.050075e+06
1,20739840,관광지,해수욕장,해수욕장,고성군,128.509936,38.356723,2021-06-01,POINT (128.509936046267 38.3567228330802),0,NaN,NaN,1.088429e+06,2.039760e+06
2,7231262,관광지,해수욕장,해수욕장,고성군,128.546412,38.300914,2021-06-01,POINT (128.546412289393 38.300913819225),0,NaN,NaN,1.091686e+06,2.033602e+06
3,11385177,관광지,일반관광지,일반관광지,고성군,128.370069,38.404499,2021-06-01,POINT (128.370069234145 38.4044988845984),0,NaN,NaN,1.076158e+06,2.044936e+06
4,14123105,관광지,토속/특산물/기념품매장,토속/특산물/기념품매장,고성군,128.535804,38.306674,2021-06-01,POINT (128.535803652593 38.3066740590294),0,NaN,NaN,1.090751e+06,2.034231e+06

In [40]:
round(df["경도_utmk"][0]), round(df["위도_utmk"][0])

(1084065, 2050075)

In [41]:
round(df["경도_utmk"][0]) / 100000

10.84065

In [ ]:
if df["경도_utmk"][0] ==